<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Computação em Nuvem III
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Introdução;</li>
  <li>Apache Spark;</li>
  <li>Data Wrangling com Spark.</li>
</ol>

---

# **Exercícios**

## 1\. Apache Spark

Replique as atividades do item 2.1 e 2.2 para instalar e configurar um cluster Apache Spark na máquina virtual do Google Colab.

> **Download Spark**

In [1]:
%%capture
!wget -q https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
!tar xf spark-3.0.0-bin-hadoop2.7.tgz && rm spark-3.0.0-bin-hadoop2.7.tgz

> **Download Java**

In [2]:
%%capture
!apt-get remove openjdk*
!apt-get update --fix-missing
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

> **Instalação do PySpark**

In [3]:
!pip install -q pyspark==3.0.0

     |████████████████████████████████| 204.7 MB 23 kB/s
     |████████████████████████████████| 198 kB 56.5 MB/s
  Building wheel for pyspark (setup.py) ... done

> **Configuração**

In [4]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.0.0-bin-hadoop2.7"

In [5]:
!pip install -q findspark==1.4.2

In [7]:
import findspark

findspark.init()

> **Conexão**

In [8]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").appName("pyspark-notebook").getOrCreate()

## 2\. Data Wrangling

A base de dados presente neste [link](https://www.kaggle.com/datasets/bank-of-england/a-millennium-of-macroeconomic-data) contem dados macroeconômicos sobre o Reino Unido desde o século 13.

**2.1\. Data**

Faça o download dos dados utilizando a máquina virutal do Google Colab com o código abaixo.

In [9]:
!wget -q "https://raw.githubusercontent.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker/master/build/workspace/data/uk-macroeconomic-data.csv" -O "uk-macroeconomic-data.csv"

**2.2. Wrangling**

Processe os dados para que a base de dados final apresente os valores da taxa de desemprego (`Unemployment rate`) e população (`Population (GB+NI)`) estejam ordenados por ano decrescente:

```csv
year,population,unemployment_rate
...,...,...
```

Para isso, utilize:

 - Pandas

In [65]:
import pandas as pd

dados_macroeconomicos_UK = pd.read_csv('uk-macroeconomic-data.csv')
dados_macroeconomicos_UK.head(3)

,Description,Real GDP of England at market prices,Real GDP of England at factor cost,"Real UK GDP at market prices, geographically-consistent estimate based on post-1922 borders","Real UK GDP at factor cost, geographically-consistent estimate based on post-1922 borders","Index of real UK GDP at factor cost - based on changing political boundaries,",Composite estimate of English and (geographically-consistent) UK real GDP at factor cost,HP-filter of log of real composite estimate of English and UK real GDP at factor cost,"Real UK gross disposable national income at market prices, constant border estimate",Real consumption,...,UK Public sector debt.1,UK Public sector debt.2,Central Government Gross Debt,Central Government Gross Debt.1,Trade deficit,Trade deficit.1,Current account,Current account .1,Current account deficit including estimated non-monetary bullion flows,Current account deficit including estimated non-monetary bullion flows.1
0,Units,"£mn, Chained Volume measure, 2013 prices","£mn, Chained Volume measure, 2013 prices","£mn, Chained Volume measure, 2013 prices","£mn, Chained Volume measure, 2013 prices","GB before 1801, GB+Ireland 1801-1920, GB + Nor...",2013=100,approx. % difference from trend,"£mn, Chained Volume measure, 2013 prices. Nom...","£mn, Chained Volume measure, 2013 prices",...,as a % of nominal GDP: measure 1,as a % of nominal GDP: measure 2,"Financial year end, nominal par value £mn","Financial year end, market value £mn",£mn,as a % of nominal GDP,£mn,as a % of nominal GDP,£mn,as a % of nominal GDP
1,1209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
dados_macroeconomicos_UK = dados_macroeconomicos_UK.loc[1:]
colunas_interesse = ['Description', 'Population (GB+NI)', 'Unemployment rate']
dados_macroeconomicos_UK = dados_macroeconomicos_UK[colunas_interesse].dropna().sort_values('Description', ascending=False)
dados_macroeconomicos_UK

    Description Population (GB+NI) Unemployment rate
808        2016              65573              4.90
807        2015              65110              5.38
806        2014              64597              6.18
805        2013              64106              7.61
804        2012              63705              7.97
..          ...                ...               ...
651        1859              24138              3.27
650        1858              23914              5.23
649        1857              23689              3.95
648        1856              23466              3.52
647        1855              23241              3.73

[162 rows x 3 columns]

In [67]:
dados_macroeconomicos_UK.columns = ['Year', 'Population', 'Unemployment rate']
dados_macroeconomicos_UK.head(3)

     Year Population Unemployment rate
808  2016      65573              4.90
807  2015      65110              5.38
806  2014      64597              6.18

In [69]:
dados_macroeconomicos_UK.to_csv('uk-macroeconomic-data-cleaned.csv', index=False)

 - PySpark

In [46]:
dados_macroeconomicos_UK = spark.read.csv(
    path='uk-macroeconomic-data.csv',
    sep=',',
    header=True    
)

dados_macroeconomicos_UK.show(n=4)

+-----------+------------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+--------------------+--------------------+--------------------------+-------------------------------------------------+--------------------+--------------------+---------------------------------------+-------------------------------+---------------------------------+------------------+--------------------+----------+-----------------+---------------------------+-------------------------------+----------+--------------------+---------------------+-------------------------------------------+-----------------------------+-------------+-------------+--------------+------------+--------------------+--------------------+------------------------+----------------------+------------------------------+------------+--------------------+------------------------------------------+------------------------------------------+--------------------+-----------------------------------+---------------------+--------------------+--------------------+----------------------+--------------------+--------------------+--------------------+-------------+--------------+-----------------------------+-------------------------------+-----------------------------------------------+-----------------------------+-------------+-------------+-------------+---------------------------------------+-----------------------------------------+----------------------------+------------------------------+-----------------------------------------+-------------------------------------------+---------------------+-----------------------+-----------------------+-----------------------------+-------------------------------+-------------+--------------------+----------------+--------------------+----------------------------------------------------------------------+------------------------------------------------------------------------+
|Description|Real GDP of England at market prices|Real GDP of England at factor cost |Real UK GDP at market prices, geographically-consistent estimate based on post-1922 borders|Real UK GDP at factor cost, geographically-consistent estimate based on post-1922 borders|Index of real UK GDP at factor cost - based on changing political boundaries, |Composite estimate of English and (geographically-consistent) UK real GDP at factor cost|HP-filter of log of real composite estimate of English and UK real GDP at factor cost|Real UK gross disposable national income at market prices, constant border estimate|    Real consumption|     Real investment|Stockbuilding contribution|Real government consumption of goods and services|      Export volumes|      Import volumes|Nominal GDP of England at market prices|Nominal UK GDP at market prices|Nominal UK GDP at market prices.1|Population (GB+NI)|Population (England)|Employment|Unemployment rate|Average weekly hours worked|Capital Services, whole economy|TFP growth| Labour productivity|Labour productivity.1|Labour share, whole economy excluding rents|GDP deflator at market prices|Export prices|Import prices|Terms of Trade|$ Oil prices|   Earnings per head|Consumer price index|Consumer price inflation|Real consumption wages|Wholesale/producer price index|   Bank Rate|         Bank Rate.1|10 year/medium-term government bond yields|Consols / long-term government bond yields|      Mortgage rates|Corporate borrowing rate from banks|Corporate bond yields|        Share prices|   $/£ exchange rate|Real $/£ exchange rate|         Nominal ERI|            Real ERI|   House price index|      Credit |Secured credit|Bank of England Balance sheet|Bank of England Balance sheet.1|Coin in circulation outside the Bank of England|Notes and coin in circulation|Monetary base|           M1| Broad Money |Public sector Total Managed Expenditure|Public sector Total Managed Expenditure.1|Public Sector Total Receipts|Public Sector Total Receipts.1|Public Sector Net Lending(+)/Borrowing(-)|Public Sector Net Lending(+)/Borrowing(-).1|UK Public sector debt|UK Public sector debt.1|UK Public sector debt.2|Central Government Gross Debt|Central Government Gross Debt.1|Trade deficit|     Trade deficit.1|Current account |  Current account .1|Current account deficit including estimated non-monetary bullion flows|Current account deficit including estimated non-monetary bullion flows.1|
+-----------+------------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+--------------------+--------------------+--------------------------+-------------------------------------------------+--------------------+--------------------+---------------------------------------+-------------------------------+---------------------------------+------------------+--------------------+----------+-----------------+---------------------------+-------------------------------+----------+--------------------+---------------------+-------------------------------------------+-----------------------------+-------------+-------------+--------------+------------+--------------------+--------------------+------------------------+----------------------+------------------------------+------------+--------------------+------------------------------------------+------------------------------------------+--------------------+-----------------------------------+---------------------+--------------------+--------------------+----------------------+--------------------+--------------------+--------------------+-------------+--------------+-----------------------------+-------------------------------+-----------------------------------------------+-----------------------------+-------------+-------------+-------------+---------------------------------------+-----------------------------------------+----------------------------+------------------------------+-----------------------------------------+-------------------------------------------+---------------------+-----------------------+-----------------------+-----------------------------+-------------------------------+-------------+--------------------+----------------+--------------------+----------------------------------------------------------------------+------------------------------------------------------------------------+
|      Units|                £mn, Chained Volu...|               £mn, Chained Volu...|                                                                       £mn, Chained Volu...|                                                                     £mn, Chained Volu...|                                                          GB before 1801, G...|                                                                                2013=100|                                                                 approx. % differe...|                                                               £mn, Chained Volu...|£mn, Chained Volu...|£mn, Chained Volu...|      pp contribution t...|                             £mn, Chained Volu...|£mn, Chained Volu...|£mn, Chained Volu...|                                    £mn|                            £mn|                              £mn|              000s|                000s|      000s|                %|                      hours|               £mn, 2013 prices|         %|Real GDP per head...| Real GDP per hour...|                       share of GDP excl...|                     2013=100|     2013=100|     2013=100|      2013=100|$ per barrel|Average weekly ea...|            2015=100|                       %|              1900=100|                      2010=100|% end period|%, calendar year ...|                      %, calendar year ...|                      %, calendar year ...|%, calendar year ...|               %, calendar year ...| %, calendar year ...|April 1962=100, Y...|Calendar year ave...|  Calendar year ave...|Calendar year ave...|Calendar year ave...|Calendar year ave...|Year end, £mn| Year end, £mn|             % of nominal GDP|               % of nominal GDP|                                  Year end, £mn|                Year end, £mn|Year end, £mn|Year end, £mn|Year end, £mn|                   Calendar year tot...|                     as a % of nominal...|        Calendar year tot...|          as a % of nominal...|                     Calendar year tot...|                       as a % of nominal...| Calendar Year end...|   as a % of nominal...|   as a % of nominal...|         Financial year en...|           Financial year en...|          £mn|as a % of nominal...|             £mn|as a % of nominal...|                                                                   £mn|                                                    as a % of nominal...|
|       1209|                                null|                               null|                                                                                       null|                                                                                     null|                                                                          null|                                                                                    null|                                                                                 null|                                                                               null|                null|                null|                      null|                                             null|                null|                null|                                   null|                           null|                             null|              null|                3626|      null|             null|                       null|                           null|      null|                null|                 null|                                       null|                         null|         null|         null|          null|        null|               0.034|                0.08|                    null|                 51.79|                          null|        null|                null|                                      null|                                      null|                null|                               null|                 null|                null|                null|                  null|                null|                null|                null|         null|          null|                         null|                           null|                                           null|                         null|         null|         null|         null|                                   null|                                     null|                        null|                          null|                                     null|                                       null|                 null|                   null|                   null|                         null|                           null|         null|                null|            null|                null|                                                                  null|                                                                    null|
|       1210|                                null|                               null|                                                                                       null|                                                                                     null|                                                                          null|                                                                                    null|                                                                                 null|                                                                               null|                null|                null|                      null|                                             null|                null|                null|                                   null|                           null|                             null|              null|                3656|      null|             null|                       null|                           null|      null|                null|                 null|                                       null|                         null|         null|         null|          null|        null|               0.030|                0.08|                    2.58|                 44.65|                          null|        null|                null|                                      null|                                      null|                null|                               null|                 null|                null|                null|                  null|                null|                null|                null|         null|          null|                         null|                           null|                                           null|                         null|         null|         null|         null|                                   null|                                     null|                        null|                          null|                                     null|                                       null|                 null|                   null|                   null|                         null|                           null|         null|                null|            null|                null|                                                                  null|                                                                    null|
|       1211|                                null|                               null|                                                                                       null|                                                                                     null|                                                                          null|                                                                                    null|                                                                                 null|                                                                               null|                null|                null|                      null|                                             null|                null|                null|                                   null|                           null|                             null|              null|                3686|      null|             null|                       null|                           null|      null|                null|                 null|                                       null|                         null|         null|         null|          null|        null|               0.026|                0.09|                   12.22|                 34.86|                          null|        null|                null|                                      null|                                      null|                null|                               null|                 null|                null|                null|                  null|                null|                null|                null|         null|          null|                         null|                           null|                                           null|                         null|         null|         null|         null|                                   null|                                     null|                        null|                          null|                                     null|                                       null|                 null|                   null|                   null|                         null|                           null|         null|                null|            null|                null|                                                                  null|                                                                    null|
+-----------+------------------------------------+-----------------------------------+-------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+--------------------+--------------------+--------------------------+-------------------------------------------------+--------------------+--------------------+---------------------------------------+-------------------------------+---------------------------------+------------------+--------------------+----------+-----------------+---------------------------+-------------------------------+----------+--------------------+---------------------+-------------------------------------------+-----------------------------+-------------+-------------+--------------+------------+--------------------+--------------------+------------------------+----------------------+------------------------------+------------+--------------------+------------------------------------------+------------------------------------------+--------------------+-----------------------------------+---------------------+--------------------+--------------------+----------------------+--------------------+--------------------+--------------------+-------------+--------------+-----------------------------+-------------------------------+-----------------------------------------------+-----------------------------+-------------+-------------+-------------+---------------------------------------+-----------------------------------------+----------------------------+------------------------------+-----------------------------------------+-------------------------------------------+---------------------+-----------------------+-----------------------+-----------------------------+-------------------------------+-------------+--------------------+----------------+--------------------+----------------------------------------------------------------------+------------------------------------------------------------------------+
only showing top 4 rows

In [47]:
dados_macroeconomicos_UK.printSchema()

root
 |-- Description: string (nullable = true)
 |-- Real GDP of England at market prices: string (nullable = true)
 |-- Real GDP of England at factor cost : string (nullable = true)
 |-- Real UK GDP at market prices, geographically-consistent estimate based on post-1922 borders: string (nullable = true)
 |-- Real UK GDP at factor cost, geographically-consistent estimate based on post-1922 borders: string (nullable = true)
 |-- Index of real UK GDP at factor cost - based on changing political boundaries, : string (nullable = true)
 |-- Composite estimate of English and (geographically-consistent) UK real GDP at factor cost: string (nullable = true)
 |-- HP-filter of log of real composite estimate of English and UK real GDP at factor cost: string (nullable = true)
 |-- Real UK gross disposable national income at market prices, constant border estimate: string (nullable = true)
 |-- Real consumption: string (nullable = true)
 |-- Real investment: string (nullable = true)
 |-- Stockbuilding contribution: string (nullable = true)
 |-- Real government consumption of goods and services: string (nullable = true)
 |-- Export volumes: string (nullable = true)
 |-- Import volumes: string (nullable = true)
 |-- Nominal GDP of England at market prices: string (nullable = true)
 |-- Nominal UK GDP at market prices: string (nullable = true)
 |-- Nominal UK GDP at market prices.1: string (nullable = true)
 |-- Population (GB+NI): string (nullable = true)
 |-- Population (England): string (nullable = true)
 |-- Employment: string (nullable = true)
 |-- Unemployment rate: string (nullable = true)
 |-- Average weekly hours worked: string (nullable = true)
 |-- Capital Services, whole economy: string (nullable = true)
 |-- TFP growth: string (nullable = true)
 |-- Labour productivity: string (nullable = true)
 |-- Labour productivity.1: string (nullable = true)
 |-- Labour share, whole economy excluding rents: string (nullable = true)
 |-- GDP deflator at market prices: string (nullable = true)
 |-- Export prices: string (nullable = true)
 |-- Import prices: string (nullable = true)
 |-- Terms of Trade: string (nullable = true)
 |-- $ Oil prices: string (nullable = true)
 |-- Earnings per head: string (nullable = true)
 |-- Consumer price index: string (nullable = true)
 |-- Consumer price inflation: string (nullable = true)
 |-- Real consumption wages: string (nullable = true)
 |-- Wholesale/producer price index: string (nullable = true)
 |-- Bank Rate: string (nullable = true)
 |-- Bank Rate.1: string (nullable = true)
 |-- 10 year/medium-term government bond yields: string (nullable = true)
 |-- Consols / long-term government bond yields: string (nullable = true)
 |-- Mortgage rates: string (nullable = true)
 |-- Corporate borrowing rate from banks: string (nullable = true)
 |-- Corporate bond yields: string (nullable = true)
 |-- Share prices: string (nullable = true)
 |-- $/£ exchange rate: string (nullable = true)
 |-- Real $/£ exchange rate: string (nullable = true)
 |-- Nominal ERI: string (nullable = true)
 |-- Real ERI: string (nullable = true)
 |-- House price index: string (nullable = true)
 |-- Credit : string (nullable = true)
 |-- Secured credit: string (nullable = true)
 |-- Bank of England Balance sheet: string (nullable = true)
 |-- Bank of England Balance sheet.1: string (nullable = true)
 |-- Coin in circulation outside the Bank of England: string (nullable = true)
 |-- Notes and coin in circulation: string (nullable = true)
 |-- Monetary base: string (nullable = true)
 |-- M1: string (nullable = true)
 |-- Broad Money : string (nullable = true)
 |-- Public sector Total Managed Expenditure: string (nullable = true)
 |-- Public sector Total Managed Expenditure.1: string (nullable = true)
 |-- Public Sector Total Receipts: string (nullable = true)
 |-- Public Sector Total Receipts.1: string (nullable = true)
 |-- Public Sector Net Lending(+)/Borrowing(-): string (nullable = true)
 |-- Public Sector Net Lending(+)/Borrowing(-).1: string (nullable = true)
 |-- UK Public sector debt: string (nullable = true)
 |-- UK Public sector debt.1: string (nullable = true)
 |-- UK Public sector debt.2: string (nullable = true)
 |-- Central Government Gross Debt: string (nullable = true)
 |-- Central Government Gross Debt.1: string (nullable = true)
 |-- Trade deficit: string (nullable = true)
 |-- Trade deficit.1: string (nullable = true)
 |-- Current account : string (nullable = true)
 |-- Current account .1: string (nullable = true)
 |-- Current account deficit including estimated non-monetary bullion flows: string (nullable = true)
 |-- Current account deficit including estimated non-monetary bullion flows.1: string (nullable = true)

In [48]:
dados_macroeconomicos_UK = dados_macroeconomicos_UK.select(
    ['Description', 'Population (GB+NI)', 'Unemployment rate']
)

In [49]:
dados_macroeconomicos_UK = dados_macroeconomicos_UK.\
    withColumnRenamed('Description', 'Year').\
    withColumnRenamed('Population (GB+NI)', 'Population')

In [50]:
dados_macroeconomicos_UK.show(n=4)

+-----+----------+-----------------+
| Year|Population|Unemployment rate|
+-----+----------+-----------------+
|Units|      000s|                %|
| 1209|      null|             null|
| 1210|      null|             null|
| 1211|      null|             null|
+-----+----------+-----------------+
only showing top 4 rows

In [52]:
from pyspark.sql.functions import broadcast

In [55]:
dados_macroeconomicos_UK_linha_descricao = dados_macroeconomicos_UK.\
    filter(dados_macroeconomicos_UK['Year'] == 'Units')

In [56]:
dados_macroeconomicos_UK = dados_macroeconomicos_UK.join(
    other=broadcast(dados_macroeconomicos_UK_linha_descricao), 
    on=['year'], 
    how='left_anti'
)

In [57]:
dados_macroeconomicos_UK.show(n=3)

+----+----------+-----------------+
|Year|Population|Unemployment rate|
+----+----------+-----------------+
|1209|      null|             null|
|1210|      null|             null|
|1211|      null|             null|
+----+----------+-----------------+
only showing top 3 rows

In [63]:
dados_macroeconomicos_UK.sort(dados_macroeconomicos_UK.Year.desc()).show(n=3)

+----+----------+-----------------+
|Year|Population|Unemployment rate|
+----+----------+-----------------+
|2016|     65573|             4.90|
|2015|     65110|             5.38|
|2014|     64597|             6.18|
+----+----------+-----------------+
only showing top 3 rows

In [64]:
dados_macroeconomicos_UK.\
    write.csv(path="uk-macroeconomic-data-clean", sep=",", header=True, mode="overwrite")